### ISSUE TITLE
Mod bugging

### ISSUE THREAD

**Issue by RDIL** [InventivetalentDev/FairySoulHelperMod#1]
Console output:
```java
17:27:30.203
[17:27:30] [Netty Client IO #1/INFO] [FML]: Aborting client handshake "VANILLA"
17:27:30.205
[17:27:30] [Netty Client IO #1/INFO] [FML]: [Netty Client IO #1] Client side vanilla connection established
17:27:31.870
[17:27:31] [main/INFO] [STDERR]: [org.inventivetalent.hypixel.fairysoulhelper.SpawnListener:on:62]: java.lang.NoSuchFieldException: fxLayers
17:27:31.871
[17:27:31] [main/INFO] [STDERR]: [org.inventivetalent.hypixel.fairysoulhelper.SpawnListener:on:62]: 	at java.lang.Class.getDeclaredField(Class.java:2070)
17:27:31.871
[17:27:31] [main/INFO] [STDERR]: [org.inventivetalent.hypixel.fairysoulhelper.SpawnListener:on:62]: 	at org.inventivetalent.hypixel.fairysoulhelper.SpawnListener.on(SpawnListener.java:51)
17:27:31.871
[17:27:31] [main/INFO] [STDERR]: [org.inventivetalent.hypixel.fairysoulhelper.SpawnListener:on:62]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_36_SpawnListener_on_ClientTickEvent.invoke(.dynamic)
17:27:31.871
[17:27:31] [main/INFO] [STDERR]: [org.inventivetalent.hypixel.fairysoulhelper.SpawnListener:on:62]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
17:27:31.871
[17:27:31] [main/INFO] [STDERR]: [org.inventivetalent.hypixel.fairysoulhelper.SpawnListener:on:62]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
17:27:31.871
[17:27:31] [main/INFO] [STDERR]: [org.inventivetalent.hypixel.fairysoulhelper.SpawnListener:on:62]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)
17:27:31.872
[17:27:31] [main/INFO] [STDERR]: [org.inventivetalent.hypixel.fairysoulhelper.SpawnListener:on:62]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1707)
17:27:31.872
[17:27:31] [main/INFO] [STDERR]: [org.inventivetalent.hypixel.fairysoulhelper.SpawnListener:on:62]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
17:27:31.872
[17:27:31] [main/INFO] [STDERR]: [org.inventivetalent.hypixel.fairysoulhelper.SpawnListener:on:62]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
17:27:31.872
[17:27:31] [main/INFO] [STDERR]: [org.inventivetalent.hypixel.fairysoulhelper.SpawnListener:on:62]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
17:27:31.872
[17:27:31] [main/INFO] [STDERR]: [org.inventivetalent.hypixel.fairysoulhelper.SpawnListener:on:62]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
17:27:31.874
[17:27:31] [main/INFO] [STDERR]: [org.inventivetalent.hypixel.fairysoulhelper.SpawnListener:on:62]: 	at 
```

and it literally just keeps on going
cc @InventivetalentDev

**Comment by InventivetalentDev** [comment]
Hmm are you on 1.12.2?

**Comment by RDIL** [comment]
Yup

**Comment by InventivetalentDev** [comment]
Oops, I guess I forgot about forge's obfuscation (so it only worked properly in my dev environment). Will fix!

**Comment by RDIL** [comment]
So it works now, but it doesn't show nametags on the armorstands, and doesn't do anything if optifine is loaded :(

**Comment by RDIL** [comment]
Closing until I can test again.
